name: 'Slack Notification'
description: 'Notifications with Mentions and Approval links'
inputs:
  status:
    description: 'Job status (success, failure, cancelled, approval)'
    required: true
  slack_webhook:
    description: 'The Slack Webhook URL'
    required: true
  job_name:
    description: 'Name of the Job being executed'
    required: false
    default: 'CI/CD Pipeline'
  mention_on_failure:
    description: 'Slack ID or Group to mention on failure'
    required: false
    default: '<!here>' 
  custom_text:
    description: 'Optional extra text to display in the message'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Send Notification
      shell: bash
      env:
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        STATUS: ${{ inputs.status }}
        JOB_NAME: ${{ inputs.job_name }}
        MENTION: ${{ inputs.mention_on_failure }}
        CUSTOM_TEXT: ${{ inputs.custom_text }}
      run: |
        # 1. Logic for Colors, Emojis
        MENTION_TEXT=""
        BUTTON_TEXT="View Logs"
        BUTTON_STYLE="primary"
        
        if [ "$STATUS" == "success" ]; then
          COLOR="#36a64f"
          EMOJI="✅"
          HEADER="Deployment Successful"
          
        elif [ "$STATUS" == "failure" ]; then
          COLOR="#dc3545"
          EMOJI="🚨"
          HEADER="Deployment Failed"
          MENTION_TEXT="$MENTION" 
          BUTTON_STYLE="danger"
          CUSTOM_TEXT=""
          
        elif [ "$STATUS" == "approval" ]; then
          COLOR="#ffc107"
          EMOJI="✋"
          HEADER="Approval Required"
          BUTTON_TEXT="Review & Approve"
          MENTION_TEXT="$MENTION"
          CUSTOM_TEXT="" 
          
        elif [ "$STATUS" == "started" ]; then
          COLOR="#2196F3"
          EMOJI="🚀"
          HEADER="Deployment Started"
          MENTION_TEXT=""
          CUSTOM_TEXT=""

        elif [ "$STATUS" == "rejected" ]; then
          COLOR="#820000"
          EMOJI="🚫"
          HEADER="Deployment Rejected"
          MENTION_TEXT="$MENTION"
          BUTTON_STYLE="danger"
          CUSTOM_TEXT=""

        elif [ "$STATUS" == "pr" ]; then
          COLOR="#9C27B0"
          EMOJI="🔀"
          HEADER="PR Validation"
          BUTTON_TEXT="View Pull Request"
          MENTION_TEXT=""
          
        else
          COLOR="#808080"
          EMOJI="⚪"
          HEADER="Build Cancelled"
          CUSTOM_TEXT=""
        fi

        # 2. Git Metadata & Event Data
        REPO_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
        RUN_URL="$REPO_URL/actions/runs/$GITHUB_RUN_ID"
        AUTHOR="$GITHUB_ACTOR"
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        TIMESTAMP=$(date +%s)
        
        # Default Button URL (Points to Logs)
        BUTTON_URL="$RUN_URL"

        # 🟢 SMART LOGIC: PR Data Extraction
        if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
          # 1. Get PR Title (Fixes the "Merge..." message)
          RAW_MSG=$(jq -r .pull_request.title "$GITHUB_EVENT_PATH")
          
          # 2. Get PR Number and construct Real URL (Fixes the Button Link)
          PR_NUM=$(jq -r .pull_request.number "$GITHUB_EVENT_PATH")
          BRANCH="PR #$PR_NUM"
          BUTTON_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/$PR_NUM"
          
        else
          # Fallback for Push events (Use Git Log)
          RAW_MSG=$(git log -1 --pretty=format:"%s")
          BRANCH="${GITHUB_REF#refs/heads/}"
        fi

        # Clean the message (Remove quotes, truncate to 50 chars)
        FULL_MSG=$(echo "$RAW_MSG" | sed 's/"/\\"/g')
        CLEAN_MSG=$(echo "$FULL_MSG" | head -n 1 | cut -c1-50)

        # 3. Handle Custom Text
        if [ -n "$CUSTOM_TEXT" ]; then
           TEXT_BLOCK="{ \"type\": \"divider\" }, { \"type\": \"section\", \"text\": { \"type\": \"mrkdwn\", \"text\": \"ℹ️ $CUSTOM_TEXT\" } },"
        else
           TEXT_BLOCK=""
        fi

        # 4. Construct Payload
        # Note: We now use $BUTTON_URL for the button action
        PAYLOAD=$(cat <<EOF
        {
          "attachments": [
            {
              "color": "$COLOR",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "$MENTION_TEXT $EMOJI *$HEADER* |  *Pipeline:* $JOB_NAME"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    { "type": "mrkdwn", "text": "*Repo:*\n<$REPO_URL|$GITHUB_REPOSITORY>" },
                    { "type": "mrkdwn", "text": "*Ref:*\n\`$BRANCH\`" },
                    { "type": "mrkdwn", "text": "*Commit:*\n<$COMMIT_URL|$SHORT_SHA> - $CLEAN_MSG" },
                    { "type": "mrkdwn", "text": "*Triggered By:*\n$AUTHOR" }
                  ]
                },
                $TEXT_BLOCK
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": { "type": "plain_text", "text": "$BUTTON_TEXT", "emoji": true },
                      "style": "$BUTTON_STYLE",
                      "url": "$BUTTON_URL"
                    }
                  ]
                },
                {
                  "type": "context",
                  "elements": [
                    { 
                      "type": "mrkdwn", 
                      "text": "Vonage Enterprise CI/CD Hub • <!date^${TIMESTAMP}^{date} at {time}|${TIMESTAMP}>" 
                    }
                  ]
                }
              ]
            }
          ]
        }
        EOF
        )

        curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" "$SLACK_WEBHOOK"