name: 'Slack Notification'
description: 'Notifications with Mentions and Approval links'
inputs:
  status:
    description: 'Job status (success, failure, cancelled, approval)'
    required: true
  slack_webhook:
    description: 'The Slack Webhook URL'
    required: true
  job_name:
    description: 'Name of the Job being executed'
    required: false
    default: 'CI/CD Pipeline'
  mention_on_failure:
    description: 'Slack ID or Group to mention on failure'
    required: false
    default: '<!here>' 
  custom_text:
    description: 'Optional extra text to display in the message'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Send Notification
      shell: bash
      env:
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        STATUS: ${{ inputs.status }}
        JOB_NAME: ${{ inputs.job_name }}
        MENTION: ${{ inputs.mention_on_failure }}
        CUSTOM_TEXT: ${{ inputs.custom_text }}
      run: |
        # 1. Logic for Colors, Emojis, and styles
        MENTION_TEXT=""
        BUTTON_TEXT="View Logs"
        BUTTON_STYLE="primary" # Default Green for Block Kit
        
        if [ "$STATUS" == "success" ]; then
          COLOR="#36a64f" # Green
          EMOJI="✅"
          HEADER="Deployment Successful"
          
        elif [ "$STATUS" == "failure" ]; then
          COLOR="#dc3545" # Red
          EMOJI="🚨"
          HEADER="Deployment Failed"
          MENTION_TEXT="$MENTION" 
          BUTTON_STYLE="danger" # Red Button
          
        elif [ "$STATUS" == "approval" ]; then
          COLOR="#ffc107" # Amber
          EMOJI="✋"
          HEADER="Approval Required"
          BUTTON_TEXT="Review & Approve"
          MENTION_TEXT="$MENTION"
          
        elif [ "$STATUS" == "started" ]; then
          COLOR="#2196F3" # Blue
          EMOJI="🚀"
          HEADER="Deployment Started"
          MENTION_TEXT="" 

        elif [ "$STATUS" == "rejected" ]; then
          COLOR="#820000" # Maroon
          EMOJI="🚫"
          HEADER="Deployment Rejected"
          MENTION_TEXT="$MENTION"
          BUTTON_STYLE="danger"
          
        else
          COLOR="#808080" # Gray
          EMOJI="⚪"
          HEADER="Build Cancelled"
        fi

        # 2. Git Metadata
        REPO_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
        RUN_URL="$REPO_URL/actions/runs/$GITHUB_RUN_ID"
        COMMIT_URL="$REPO_URL/commit/$GITHUB_SHA"
        AUTHOR="$GITHUB_ACTOR"
        BRANCH="${GITHUB_REF#refs/heads/}"
        MESSAGE=$(git log -1 --pretty=format:"%s" || echo "No commit message")
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        DATE=$(date "+%Y-%m-%d %H:%M:%S")

        # 3. Handle Optional Custom Text
        # If custom text exists, we format it as a distinct section
        if [ -n "$CUSTOM_TEXT" ]; then
          TEXT_BLOCK="{ \"type\": \"section\", \"text\": { \"type\": \"mrkdwn\", \"text\": \"$CUSTOM_TEXT\" } },"
        else
          TEXT_BLOCK=""
        fi

        # 4. Construct Block Kit Payload
        # We nest 'blocks' inside 'attachments' to keep the side Color Bar
        PAYLOAD=$(cat <<EOF
        {
          "attachments": [
            {
              "color": "$COLOR",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "$EMOJI $HEADER",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Pipeline:* $JOB_NAME\n$MENTION_TEXT"
                  }
                },
                {
                  "type": "divider"
                },
                $TEXT_BLOCK
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n<$REPO_URL|$GITHUB_REPOSITORY>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Reference:*\n\`$BRANCH\`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:*\n<$COMMIT_URL|$SHORT_SHA>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered By:*\n$AUTHOR"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "$BUTTON_TEXT",
                        "emoji": true
                      },
                      "style": "$BUTTON_STYLE",
                      "url": "$RUN_URL"
                    }
                  ]
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Vonage Enterprise CI/CD Hub • $DATE"
                    }
                  ]
                }
              ]
            }
          ]
        }
        EOF
        )

        curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" "$SLACK_WEBHOOK"