name: 'Slack Notification'
description: 'Notifications with Mentions and Approval links'
inputs:
  status:
    description: 'Job status (success, failure, cancelled, approval)'
    required: true
  slack_webhook:
    description: 'The Slack Webhook URL'
    required: true
  job_name:
    description: 'Name of the Job being executed'
    required: false
    default: 'CI/CD Pipeline'
  mention_on_failure:
    description: 'Slack ID or Group to mention on failure'
    required: false
    default: '<!here>' 

runs:
  using: "composite"
  steps:
    - name: Send Notification
      shell: bash
      env:
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        STATUS: ${{ inputs.status }}
        JOB_NAME: ${{ inputs.job_name }}
        MENTION: ${{ inputs.mention_on_failure }}
      run: |
        # 1. Logic for Colors, Emojis, and Mentions
        MENTION_TEXT=""
        BUTTON_TEXT="View Logs"
        BUTTON_STYLE="primary"
        
        if [ "$STATUS" == "success" ]; then
          COLOR="#36a64f" # Green
          EMOJI=":white_check_mark:"
          HEADER="Build Succeeded"
          
        elif [ "$STATUS" == "failure" ]; then
          COLOR="#dc3545" # Red
          EMOJI=":x:"
          HEADER="Build Failed"
          MENTION_TEXT="$MENTION " 
          BUTTON_STYLE="danger"
          
        elif [ "$STATUS" == "approval" ]; then
          COLOR="#ffc107" # Amber/Yellow
          EMOJI=":raised_hand:"
          HEADER="Approval Required"
          BUTTON_TEXT="Review & Approve"
          MENTION_TEXT="$MENTION "

        elif [ "$STATUS" == "rejected" ]; then
          COLOR="#820000" # Dark Red / Maroon (Distinct from failure)
          EMOJI=":no_entry_sign:" # Stop sign symbol
          HEADER="Deployment Rejected"
          MENTION_TEXT="$MENTION "
          
        else
          COLOR="#808080" # Gray
          EMOJI=":bow:"
          HEADER="Build Cancelled"
        fi

        # 2. Git Metadata
        REPO_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
        RUN_URL="$REPO_URL/actions/runs/$GITHUB_RUN_ID"
        COMMIT_URL="$REPO_URL/commit/$GITHUB_SHA"
        AUTHOR="$GITHUB_ACTOR"
        BRANCH="${GITHUB_REF#refs/heads/}"
        MESSAGE=$(git log -1 --pretty=format:"%s" || echo "No commit message")

        # 3. Construct Payload
        # We prepend MENTION_TEXT to the pretext so it triggers a notification
        PAYLOAD=$(cat <<EOF
        {
          "attachments": [
            {
              "color": "$COLOR",
              "pretext": "$MENTION_TEXT $EMOJI *${JOB_NAME}* - $HEADER",
              "fields": [
                { "title": "Repo", "value": "<$REPO_URL|$GITHUB_REPOSITORY>", "short": true },
                { "title": "Ref", "value": "\`$BRANCH\`", "short": true },
                { "title": "Commit", "value": "<$COMMIT_URL|$(echo $GITHUB_SHA | cut -c1-7)>: $MESSAGE", "short": false },
                { "title": "Actor", "value": "$AUTHOR", "short": true }
              ],
              "actions": [
                {
                  "type": "button",
                  "text": "$BUTTON_TEXT",
                  "url": "$RUN_URL",
                  "style": "$BUTTON_STYLE"
                }
              ],
              "footer": "Vonage Enterprise CI/CD Hub",
              "ts": $(date +%s)
            }
          ]
        }
        EOF
        )

        curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" "$SLACK_WEBHOOK"